package com.ventatickets.ventaticketstaxis.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta Material 3 generada a partir de Material Theme Builder

// Light Scheme
val md_theme_light_primary = Color(0xFF0B57D0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCE2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B40)
val md_theme_light_secondary = Color(0xFF146C94)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF00263B)
val md_theme_light_tertiary = Color(0xFF2F7D4E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1F7D5)
val md_theme_light_onTertiaryContainer = Color(0xFF00210F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFF9FAFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF75777F)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFAFC7FF)
val md_theme_light_surfaceTint = md_theme_light_primary
val md_theme_light_scrim = Color(0x66000000)

// Dark Scheme
val md_theme_dark_primary = Color(0xFFAFC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F6D)
val md_theme_dark_primaryContainer = Color(0xFF094597)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE2FF)
val md_theme_dark_secondary = Color(0xFFA5C9E4)
val md_theme_dark_onSecondary = Color(0xFF00344F)
val md_theme_dark_secondaryContainer = Color(0xFF014D73)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_tertiary = Color(0xFFA5D6B0)
val md_theme_dark_onTertiary = Color(0xFF0B361E)
val md_theme_dark_tertiaryContainer = Color(0xFF1F5230)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1F7D5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8D9099)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_inverseOnSurface = Color(0xFF111318)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0B57D0)
val md_theme_dark_surfaceTint = md_theme_dark_primary
val md_theme_dark_scrim = Color(0xAA000000)

// Colores utilitarios existentes
val AdaptiveRed = Color(0xFFF44336)
val AdaptiveGreen = Color(0xFF4CAF50)